### ISSUE TITLE
03/27/2020-Team-104-The-Fornax.

### ISSUE THREAD

**Issue by tacodtripe** [Albertino2020/Smashing-magazine-clone#1]
Excellent start of the webpage, a nice implementation of the transform: rotate.
I might suggest you should focus on just the general layout of the page and defining the visual impact of every element using shades of gray.
This would make the project much easier than what you are already doing.

**Comment by rajkumardas2701** [comment]
Thank you for the suggestions Team. We have implemented page in Greyscale with focus on only important features.
